#!/usr/bin/env bash
set -euo pipefail

# Collect open issues labeled "bug" across gruted/* repos.
# Outputs markdown to stdout. Does not modify repos.
#
# Usage:
#   scripts/gh_bug_report.sh > notes/gh-bugs.md

ORG="${1:-gruted}"
LIMIT_REPOS="${LIMIT_REPOS:-200}"
LIMIT_ISSUES_PER_REPO="${LIMIT_ISSUES_PER_REPO:-100}"

if ! command -v gh >/dev/null; then
  echo "error: gh CLI not found" >&2
  exit 1
fi

utc_ts="$(date -u '+%Y-%m-%d %H:%M:%S')"

echo "# GitHub bug issues — ${ORG} — ${utc_ts} UTC"
echo
echo "Generated by scripts/gh_bug_report.sh"
echo

repos_json="$(gh repo list "$ORG" --limit "$LIMIT_REPOS" --json nameWithOwner,isArchived,isPrivate 2>/dev/null)"

echo "## Summary"
total_repos="$(echo "$repos_json" | jq 'length')"
echo "- Repos scanned: ${total_repos}"
echo

echo "$repos_json" | jq -r '.[] | select(.isArchived|not) | .nameWithOwner' | while read -r repo; do
  # Fetch bug-labeled open issues.
  issues_json="$(gh issue list --repo "$repo" --state open --limit "$LIMIT_ISSUES_PER_REPO" \
    --label bug --label enhancement --label good-first-issue \
    --json number,title,url,createdAt,updatedAt,author,assignees,labels 2>/dev/null || echo '[]')"

  count="$(echo "$issues_json" | jq 'length')"
  if [[ "$count" -eq 0 ]]; then
    continue
  fi

  echo "## ${repo} (${count})"
  echo
  echo "$issues_json" | jq -r '.[] | "- #\(.number): \(.title)\n  - url: \(.url)\n  - updated: \(.updatedAt)\n  - assignees: \([.assignees[].login] | join(", "))"'
  echo

done
