#!/usr/bin/env bash
set -euo pipefail

# Weekly machine audit -> markdown.
# Usage:
#   scripts/weekly_audit.sh                # prints markdown to stdout
#   scripts/weekly_audit.sh --out <file>   # appends a dated entry to file

OUT=""
if [[ "${1:-}" == "--out" ]]; then
  OUT="${2:-}"
  if [[ -z "$OUT" ]]; then
    echo "error: --out requires a filepath" >&2
    exit 2
  fi
fi

utc_ts="$(date -u '+%Y-%m-%d %H:%M:%S')"
host="$(hostname)"
kernel="$(uname -srmo 2>/dev/null || uname -a)"

md() {
  cat <<EOF
## Weekly Machine Audit — ${utc_ts} UTC

- Hostname: ${host}
- Kernel: ${kernel}

### Uptime / Load
\`\`\`
$(uptime 2>&1 || true)
\`\`\`

### Disk (df -hT)
\`\`\`
$(df -hT 2>&1 || true)
\`\`\`

### Memory (free -h)
\`\`\`
$(free -h 2>&1 || true)
\`\`\`

### Docker (docker ps)
\`\`\`
$(docker ps --format 'table {{.Names}}\t{{.Status}}\t{{.Image}}' 2>&1 || echo 'docker: not available')
\`\`\`

### systemd failed units
\`\`\`
$(systemctl --no-pager --failed 2>&1 || echo 'systemctl: not available')
\`\`\`

### OpenClaw nodes status
\`\`\`
$(openclaw nodes status 2>&1 || echo 'openclaw: not available')
\`\`\`

### nginx status (if present)
\`\`\`
$(systemctl --no-pager status nginx.service -l 2>&1 || true)
\`\`\`

### Notes / Actions
- [ ] Review any failed units above.
- [ ] If nginx failed: run \`sudo nginx -t\` and inspect config + logs.
- [ ] Check backups/cron logs.

EOF
}

if [[ -n "$OUT" ]]; then
  mkdir -p "$(dirname "$OUT")"
  if [[ ! -f "$OUT" ]]; then
    cat >"$OUT" <<'HDR'
# audit-weekly.md

Weekly, low-touch machine audit snapshots (generated by scripts/weekly_audit.sh).

---
HDR
  fi
  md >>"$OUT"
else
  md
fi
